env: OMP_NUM_THREADS=1
matrix:
  exclude:
    - os: osx
      compiler: gcc
branches:
  only:
    - master
    - devel
before_install:
  - ./DEPENDENCIES-INSTALLER.sh
language: cpp
script: ./.maketravis.sh
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
