env: OMP_NUM_THREADS=2 TEST_OMP=no
matrix:
  exclude:
    - os: osx
      compiler: gcc
    - os:linux
      compiler: clang
branches:
  only:
    - master
    - devel
before_install:
  - ./DEPENDENCIES-INSTALLER.sh
language: cpp
script: ./.maketravis.sh
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
