env: OMP_NUM_THREADS=4
branches:
  only:
    - master
    - devel
before_install:
  - sudo apt-get update -qq
  - sudo ./DEPENDENCIES-INSTALLER.sh
language: cpp
script: ./.maketravis.sh
compiler:
  - gcc
  - clang
